import './Sidebar.css';

export default function Sidebar({ localFilters, onFilterChange }) {

    const listOfGenres = [
        { label: "Random Genre", value: ""},
        { label: "Ambient", value: "Ambient" },
        { label: "Blues", value: "Blues" },
        { label: "Classical", value: "Classical" },
        { label: "Country", value: "Country" },
        { label: "Dance", value: "Dance" },
        { label: "Electronic", value: "Electronic" },
        { label: "Experimental", value: "Experimental" },
        { label: "Folk", value: "Folk" },
        { label: "Hip Hop", value: "Hip Hop" },
        { label: "Jazz", value: "Jazz" },
        { label: "Metal", value: "Metal" },
        { label: "Pop", value: "Pop" },
        { label: "Punk", value: "Punk" },
        { label: "R&B", value: "R&B" },
        { label: "Rock", value: "Rock"},
        { label: "Singer Songwriter", value: "Singer Songwriter" },
    ];

    const currentYear = new Date().getFullYear().toString();
    const listOfDecades = [
        { label: "All Decades", value: "" },
        { label: "2020s", value: `2020-${currentYear}` },
        { label: "2010s", value: "2010-2019" },
        { label: "2000s", value: "2000-2009" },
        { label: "1990s", value: "1990-1999" },
        { label: "1980s", value: "1980-1989" },
        { label: "1970s", value: "1970-1979" },
        { label: "1960s", value: "1960-1969" },
        { label: "1950s", value: "1950-1959" },
    ];

    const listOfMarkets = [
        { label: "United States", value: "US" },
        { label: "Andorra", value: "AD" },
        { label: "United Arab Emirates", value: "AE" },
        { label: "Antigua and Barbuda", value: "AG" },
        { label: "Albania", value: "AL" },
        { label: "Armenia", value: "AM" },
        { label: "Angola", value: "AO" },
        { label: "Argentina", value: "AR" },
        { label: "Austria", value: "AT" },
        { label: "Australia", value: "AU" },
        { label: "Azerbaijan", value: "AZ" },
        { label: "Bosnia and Herzegovina", value: "BA" },
        { label: "Barbados", value: "BB" },
        { label: "Bangladesh", value: "BD" },
        { label: "Belgium", value: "BE" },
        { label: "Burkina Faso", value: "BF" },
        { label: "Bulgaria", value: "BG" },
        { label: "Bahrain", value: "BH" },
        { label: "Burundi", value: "BI" },
        { label: "Benin", value: "BJ" },
        { label: "Brunei", value: "BN" },
        { label: "Bolivia", value: "BO" },
        { label: "Brazil", value: "BR" },
        { label: "Bahamas", value: "BS" },
        { label: "Bhutan", value: "BT" },
        { label: "Botswana", value: "BW" },
        { label: "Belarus", value: "BY" },
        { label: "Belize", value: "BZ" },
        { label: "Canada", value: "CA" },
        { label: "Congo (Democratic Republic)", value: "CD" },
        { label: "Congo (Republic)", value: "CG" },
        { label: "Switzerland", value: "CH" },
        { label: "Côte d’Ivoire", value: "CI" },
        { label: "Chile", value: "CL" },
        { label: "Cameroon", value: "CM" },
        { label: "Colombia", value: "CO" },
        { label: "Costa Rica", value: "CR" },
        { label: "Cape Verde", value: "CV" },
        { label: "Curaçao", value: "CW" },
        { label: "Cyprus", value: "CY" },
        { label: "Czech Republic", value: "CZ" },
        { label: "Germany", value: "DE" },
        { label: "Djibouti", value: "DJ" },
        { label: "Denmark", value: "DK" },
        { label: "Dominica", value: "DM" },
        { label: "Dominican Republic", value: "DO" },
        { label: "Algeria", value: "DZ" },
        { label: "Ecuador", value: "EC" },
        { label: "Estonia", value: "EE" },
        { label: "Egypt", value: "EG" },
        { label: "Spain", value: "ES" },
        { label: "Ethiopia", value: "ET" },
        { label: "Finland", value: "FI" },
        { label: "Fiji", value: "FJ" },
        { label: "Micronesia", value: "FM" },
        { label: "France", value: "FR" },
        { label: "Gabon", value: "GA" },
        { label: "United Kingdom", value: "GB" },
        { label: "Grenada", value: "GD" },
        { label: "Georgia", value: "GE" },
        { label: "Ghana", value: "GH" },
        { label: "Gambia", value: "GM" },
        { label: "Guinea", value: "GN" },
        { label: "Equatorial Guinea", value: "GQ" },
        { label: "Greece", value: "GR" },
        { label: "Guatemala", value: "GT" },
        { label: "Guinea-Bissau", value: "GW" },
        { label: "Guyana", value: "GY" },
        { label: "Hong Kong", value: "HK" },
        { label: "Honduras", value: "HN" },
        { label: "Croatia", value: "HR" },
        { label: "Haiti", value: "HT" },
        { label: "Hungary", value: "HU" },
        { label: "Indonesia", value: "ID" },
        { label: "Ireland", value: "IE" },
        { label: "Israel", value: "IL" },
        { label: "India", value: "IN" },
        { label: "Iraq", value: "IQ" },
        { label: "Iceland", value: "IS" },
        { label: "Italy", value: "IT" },
        { label: "Jamaica", value: "JM" },
        { label: "Jordan", value: "JO" },
        { label: "Japan", value: "JP" },
        { label: "Kenya", value: "KE" },
        { label: "Kyrgyzstan", value: "KG" },
        { label: "Cambodia", value: "KH" },
        { label: "Kiribati", value: "KI" },
        { label: "Comoros", value: "KM" },
        { label: "Saint Kitts and Nevis", value: "KN" },
        { label: "South Korea", value: "KR" },
        { label: "Kuwait", value: "KW" },
        { label: "Kazakhstan", value: "KZ" },
        { label: "Laos", value: "LA" },
        { label: "Lebanon", value: "LB" },
        { label: "Saint Lucia", value: "LC" },
        { label: "Liechtenstein", value: "LI" },
        { label: "Sri Lanka", value: "LK" },
        { label: "Liberia", value: "LR" },
        { label: "Lesotho", value: "LS" },
        { label: "Lithuania", value: "LT" },
        { label: "Luxembourg", value: "LU" },
        { label: "Latvia", value: "LV" },
        { label: "Libya", value: "LY" },
        { label: "Morocco", value: "MA" },
        { label: "Monaco", value: "MC" },
        { label: "Moldova", value: "MD" },
        { label: "Montenegro", value: "ME" },
        { label: "Madagascar", value: "MG" },
        { label: "Marshall Islands", value: "MH" },
        { label: "North Macedonia", value: "MK" },
        { label: "Mali", value: "ML" },
        { label: "Mongolia", value: "MN" },
        { label: "Macau", value: "MO" },
        { label: "Mauritania", value: "MR" },
        { label: "Malta", value: "MT" },
        { label: "Mauritius", value: "MU" },
        { label: "Maldives", value: "MV" },
        { label: "Malawi", value: "MW" },
        { label: "Mexico", value: "MX" },
        { label: "Malaysia", value: "MY" },
        { label: "Mozambique", value: "MZ" },
        { label: "Namibia", value: "NA" },
        { label: "Niger", value: "NE" },
        { label: "Nigeria", value: "NG" },
        { label: "Nicaragua", value: "NI" },
        { label: "Netherlands", value: "NL" },
        { label: "Norway", value: "NO" },
        { label: "Nepal", value: "NP" },
        { label: "Nauru", value: "NR" },
        { label: "New Zealand", value: "NZ" },
        { label: "Oman", value: "OM" },
        { label: "Panama", value: "PA" },
        { label: "Peru", value: "PE" },
        { label: "Papua New Guinea", value: "PG" },
        { label: "Philippines", value: "PH" },
        { label: "Pakistan", value: "PK" },
        { label: "Poland", value: "PL" },
        { label: "Puerto Rico", value: "PR" },
        { label: "Palestine", value: "PS" },
        { label: "Portugal", value: "PT" },
        { label: "Palau", value: "PW" },
        { label: "Paraguay", value: "PY" },
        { label: "Qatar", value: "QA" },
        { label: "Romania", value: "RO" },
        { label: "Serbia", value: "RS" },
        { label: "Rwanda", value: "RW" },
        { label: "Saudi Arabia", value: "SA" },
        { label: "Solomon Islands", value: "SB" },
        { label: "Seychelles", value: "SC" },
        { label: "Sweden", value: "SE" },
        { label: "Singapore", value: "SG" },
        { label: "Slovenia", value: "SI" },
        { label: "Slovakia", value: "SK" },
        { label: "Sierra Leone", value: "SL" },
        { label: "San Marino", value: "SM" },
        { label: "Senegal", value: "SN" },
        { label: "Suriname", value: "SR" },
        { label: "São Tomé and Príncipe", value: "ST" },
        { label: "El Salvador", value: "SV" },
        { label: "Eswatini", value: "SZ" },
        { label: "Chad", value: "TD" },
        { label: "Togo", value: "TG" },
        { label: "Thailand", value: "TH" },
        { label: "Tajikistan", value: "TJ" },
        { label: "Timor-Leste", value: "TL" },
        { label: "Tunisia", value: "TN" },
        { label: "Tonga", value: "TO" },
        { label: "Turkey", value: "TR" },
        { label: "Trinidad and Tobago", value: "TT" },
        { label: "Tuvalu", value: "TV" },
        { label: "Taiwan", value: "TW" },
        { label: "Tanzania", value: "TZ" },
        { label: "Ukraine", value: "UA" },
        { label: "Uganda", value: "UG" },
        { label: "Uruguay", value: "UY" },
        { label: "Uzbekistan", value: "UZ" },
        { label: "Saint Vincent and the Grenadines", value: "VC" },
        { label: "Venezuela", value: "VE" },
        { label: "Vietnam", value: "VN" },
        { label: "Vanuatu", value: "VU" },
        { label: "Samoa", value: "WS" },
        { label: "Kosovo", value: "XK" },
        { label: "South Africa", value: "ZA" },
        { label: "Zambia", value: "ZM" },
        { label: "Zimbabwe", value: "ZW" },
    ];

    const handleChange = (e) => {
        const { name, value } = e.target;
        const updatedFilters = { ...localFilters, [name]: value };
        onFilterChange(updatedFilters);
    };

    return (
        <div className="sidebar">
            <label htmlFor="genre">genre</label>
            <select name="genre" id="genre" onChange={handleChange}>
                {listOfGenres.map(genreOption => (
                    <option key={genreOption.value} value={genreOption.value}>{genreOption.label}</option>
                ))}
            </select>
            <label htmlFor="decade">decade</label>
            <select name="decade" id="decade" onChange={handleChange}>
                {listOfDecades.map(decadeOption => (
                    <option key={decadeOption.value} value={decadeOption.value}>{decadeOption.label}</option>
                ))}
            </select>
            <label htmlFor="market">market</label>
            <select name="market" id="market" onChange={handleChange}>
                {listOfMarkets.map(marketOption => (
                    <option key={marketOption.value} value={marketOption.value}>{marketOption.label}</option>
                ))}
            </select>
        </div>
    );
}